(define (problem attack1) 
    (:domain attack)
    (:objects a c1 c2 c3 c4 c5 c6 c7 c8 c9 c10)
    (:init 
        (attacker a)
        (computer c1)
        (computer c2)
        (computer c3)
        (computer c4)
        (computer c5)
        (computer c6)
        (computer c7)
        (computer c8)
        (computer c9)
        (computer c10)
        (is-windows10 c1)
        (is-windows10 c2)
        (is-windows10 c3)
        (is-windows7 c4)
        (is-windows7 c5)
        (is-windows7 c6)
        (is-ubuntu16 c7)
        (is-ubuntu16 c8)
        (is-ubuntu16 c9)
        (is-mint c10)
        (controlled-by c1 a)
        (connected-to c1 c2)
        (connected-to c2 c3)
        (connected-to c3 c4)
        (connected-to c4 c5)
        (connected-to c5 c6)
        (connected-to c6 c7)
        (connected-to c7 c8)
        (connected-to c8 c9)
        (connected-to c9 c10)
    )
    (:goal (and
        (controlled-by c10 a)
    ))
    
)
